### ISSUE TITLE
Save CW metrics using UTC instead of local time

### ISSUE THREAD

**Issue by tim-elliott** [cloud-custodian/cloud-custodian#2106]
Currently the `-m` flag to Custodian saves metrics to CloudWatch using local time.  This is fine if all Custodian runs are done on a server/instance that uses UTC, but has issues if running where a local timezone is used.  It would be useful to have an option to have Custodian save the metrics using UTC so that 1) they could be correlated with other metrics in CW without needing to know what timezone they originated in, and 2) we wouldn't have metric gaps/overlaps when DST boundaries are crossed.  For backwards compatibility this could be done using optional arguments to `-m` or by using a separate command line argument.

**Comment by kapilt** [comment]
hmm.. good catch, its been a while since i've been on a server not on utc. i'm wary of a compatibility flag here due to flag proliferation (/me looks at mysql as poster child for bug fix through flag == 100s of flags). the rest of cw metrics are in utc, so that really should be our true north wrt to tz imo. i'd be game to do to a 'hidden' environment variable and document in the release notes, to address compatibility concerns.
