### ISSUE TITLE
Feature Request: have `resource-owner` resolve ldap uids

### ISSUE THREAD

**Issue by salwandhruvdev** [cloud-custodian/cloud-custodian#2227]
`resource-owner` does not perform ldap lookups to resolve emails from a uid. 
If we were to add OwnerContact info under the `ldap_uid_tags` config, then these contacts would get mailed regardless of specifying `resource-owner` in the policy.

**Comment by kapilt** [comment]
agreed, resource-owners should only be notified if explicitly specified in policy, looks like this was a regression from a contributed refactor. there's some compatibility implications now on behavior though.

**Comment by alfredgamulo** [comment]
What is happening here is an issue when `ldap_uid_tags` shares common tags with `contact_tags` in the config..

When `resource-owner` is processed, it doesn't perform any LDAP lookups.
Instead, a separate function is processing LDAP UIDs listed under the `ldap_uid_tags` config and this method is not checking for the presence of `resource-owner` in the action and works completely independently from resource owner.

To clean this up, it would be nice to drop the `ldap_uid_tags` config and just use `contact_tags` and to automatically perform an ldap lookup if the target value was not an email format. 

Along the same lines with this issue is the hidden functionality buried in this [`get_ldap_emails_from_resource()`](https://github.com/capitalone/cloud-custodian/blob/bebe438e6ad1dcf0bfe45fc7dc48feb90429288f/tools/c7n_mailer/c7n_mailer/email_delivery.py#L112-L135)
Since there's a lot of buried configs here that I don't think is documented anywhere and seems to be very specific to the original author's usecase, would it be safe to refactor it out? It's a conflict of breaking some people using these undocumented features, and making the codebase cleaner and easier to understand.
