### ISSUE TITLE
Add 'invoke-function' action to support local functions

### ISSUE THREAD

**Issue by troylar** [cloud-custodian/cloud-custodian#2654]
We are currently running cloud-custodian in Fargate and rather than responding with an `invoke-lambda`, we'd prefer to remove the overhead of Lambda and just run the action code in the same Fargate task.

Basically, _almost_ the same functionality as the `LambdaInvoke` class, but running locally instead.

**Comment by kapilt** [comment]
its possible to do this via the extension mechanism, that the providers currently use to register themselves. all providers, resources, actions, filters are basically extensions via python's setup tools entry points. only the resource extension is loaded at runtime due to runtime costs (requires fs scan), but a single entry point can register across any extension type.
