### ISSUE TITLE
Docker image is out of date

### ISSUE THREAD

**Issue by thomasbiddle** [cloud-custodian/cloud-custodian#2672]
Could you please have your CI build and deploy the latest Docker image, as well as create a tag for each version?

https://hub.docker.com/r/capitalone/cloud-custodian/

Looks like it's over a year old currently

**Comment by kapilt** [comment]
i've been trying to get our org adminstrators to allow to add a web hook / oauth app to handle this... @SanthiSridharan

**Comment by kapilt** [comment]
up to date docker images are now available auto built from trunk and releases and available here
https://cloud.docker.com/u/cloudcustodian/repository/docker/cloudcustodian/c7n

i've deleted the old repository as the images were ancient, and as a result had plenty of known cves just due to being out of date.
