### ISSUE TITLE
azure - investigate event grid for api subscription policy lambdas

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#2697]
seems to have the nesc functionality, we would  focus on arm apis, with direct invoke to cloud function. the filtering on subscriptions isn't quite ideal due to the audit record data format, but it supports direct integration with azure functions.

**Comment by aluong** [comment]
Do you want an Event Grid to invoke a Lambda? That should be supported, because Event Grid should be able to invoke any external web hook.

**Comment by kapilt** [comment]
sorry, didn't really mean aws lambda, meant an azure cloud function, updated to reflect that. it appears to be the right path for api subscriptions, although may need some additional filtering capabilities on subscription go fine grained on particular api calls.

**Comment by kapilt** [comment]
to be clear we're looking sans web hook, direct azure function integration, to avoid public access on the event inbound interface, all of which is supported by event grid. the question atm there is the right event streams (arm is supported) and the right filtering. its pretty on filtering atm, basic string prefix/suffix/equality matching on subject only, we'd want arbitrary field to get api invoked.

**Comment by aluong** [comment]
@erwelch and I have been prototyping [Event Grid Azure Subscriptions Evebts](https://docs.microsoft.com/en-us/azure/event-grid/event-schema-subscriptions). One of the current downsides is the set of the events that are firing are mainly [writes and deletes](https://docs.microsoft.com/en-us/azure/event-grid/event-schema-subscriptions#available-event-types). In addition, the function currently has to do specific resource filtering work because of the limited filtering options supported by Event Grid. Consequently, the function will fire on all `write` events, but then it will filter based on the policy to the resource that is actually specified in the policy. Ex: `operationName: 'Microsoft.Compute/virtualMachines/write'`
