### ISSUE TITLE
plugins cannot be deployed with the current design

### ISSUE THREAD

**Issue by eamonnfaherty** [cloud-custodian/cloud-custodian#2890]
The mu package is very helpful but it only uploads files ending with py.

The current approach for deploying custom actions and filters is via the setuptools entry_points pattern.  This relies on a dist-info dir for the package containing the code containing the following files:
- INSTALLER
- METADATA
- RECORD
- WHEEL
- entry_points.txt
- top_level.txt

This means mu is not compatible with plugins.  Could you please confirm this or let me know if I am missing something or if there is another approach?

As a workaround I am downloading the lambdas using the aws cli, patching the zip and updating the code.

**Comment by kapilt** [comment]
`invoke-lambda` allows custom action w/ out of band distribution from c7n policy lambdas.

**Comment by eamonnfaherty** [comment]
Thanks for the response @kapilt 

We are using Cloud Custodian where policies are deployed as lambdas in a central account monitoring other accounts.  With this setup the invoke lambda action will run using the cross account IAM role from the policy.  We would like the invoke lambda call to run with the IAM role specified in our initial custodian run command.

**Comment by kapilt** [comment]
That brings to mind a few more questions 

 - are the custom filters/actions here specific to a particular internal integration? 
 - are they intended to be invoked in the central account or the target account? 
 - if the latter are they using custodian's builtin support for centralized exec via role assume back to target account before policy exec?
 - how are the additional packages being specified in the policy?

We generally try to support filter integrations via having separate systems drop data into s3 or pickup via url (ie value_from`) as its better decoupling without having to assume a downstream dependency on an external system (which itself may not scale). if there not particular internal we do encourage users to contribute to custodian so that others users may benefit.

The entry point stuff ends up causing significant latency in lambda for cold starts, its been something I've looked at deprecating or at least putting behind an env var. mu as a library does support arbitrary file uploading, but not as part of custodian policy.

**Comment by kapilt** [comment]
closing due to lack of response.
