### ISSUE TITLE
Documentation on extending plugins and actions

### ISSUE THREAD

**Issue by sbuehnemann** [cloud-custodian/cloud-custodian#2946]
We need a specific notification that needs to query information at runtime. So I decided to extend notify with a custom notify. As I read in http://capitalone.github.io/cloud-custodian/docs/generated/aws/c7n.html?highlight=pluggable#module-c7n.registry it should be possible to extend cloud custodian to custom requirements.

However, I have not found documentation or examples yet on how to write custom actions with a custom name and have them register successfully.

Could you point me to the relevant sections of the code? I could provide additional documentation afterwards.

**Comment by kapilt** [comment]
For custom actions on aws resources the simplest mechanism is invoke-lambda. Wrt to extending custodian the extant mechanism is documented poorly partly because it’s under consideration of being off by default. The most common usage scenario is non-public provider features, followed by custom integrations. On the filter side for the latter we prefer to decouple as an s3/url dataset via value_from syntax on a filter, for actions invoke suffices. What’s your use case?

**Comment by sbuehnemann** [comment]
When I was looking at the lambda support I did not find a way to pass arbitrary parameters, am I missing something? Could those parameters also be validated by a schema?

**Comment by kapilt** [comment]
talked with user on gitter that the supplied parameters sufficed for their use case.
