### ISSUE TITLE
azure: SQL Server and/or database retention filter and action to set

### ISSUE THREAD

**Issue by bclements** [cloud-custodian/cloud-custodian#3030]
This is a feature request. I need the sql server resource to be able to query/filter for the retention period of a sql server and/or database backup and also an action to set the retention period for the backup. 

Looks like you can query and set the retention period via the api but that functionality is not exposed in the sql server c7n resource. 

You can change the default retention using REST API or PowerShell. The supported values are: 7, 14, 21, 28 or 35 days. https://docs.microsoft.com/en-us/rest/api/sql/backupshorttermretentionpolicies/backupshorttermretentionpolicies_get

**Comment by axis7818** [comment]
I am giving this one a shot

**Comment by stefangordon** [comment]
@logachev and I were discussing that we might get a good user experience by just creating a top level SQL Database resource (which will require a bit of custom work to enumerate), which we can also include some of the SQL Server fields in (we'll already have them while enumerating) so it is more versatile.

Then the action for setting short and long term retention policies.

**Comment by axis7818** [comment]
it does seem like inspecting short & long term retention policies require another query, so I agree with creating a top level resource for SQL databases instead of having 3 layers of querying (sql server -> sql database -> retention policy). And I think I can figure out the extra enumeration work.

I did just put up a PR #3846  that adds a custom filter to `azure.sqlserver` that augments with the database models. I could imagine that would still be useful for writing policies that deal with the relationship between a server & database.

**Comment by stefangordon** [comment]
re: #3846 - Agreed both are useful.   Like if you want to find all SQL Servers with more than 10 Databases or something you'd want to use that one.

**Comment by axis7818** [comment]
scratch #3846, moving forward with the approach in #3853

**Comment by logachev** [comment]
Thanks @axis7818 !
@bclements now we have a support for retention policies filters & actions
