### ISSUE TITLE
Skipping failed operation - Allow invoke action for an event having errorCode

### ISSUE THREAD

**Issue by ragunathp** [cloud-custodian/cloud-custodian#3122]
Our use case:  
Send a notification whenever a client application uses a Customer Master Key (KMS) that has been marked as **"pending deletion"**.

Whenever a client (for e.g. aws cli kms encrypt....) uses the key that is marked for deletion, a cloudTrail/CloudWatch event is generated with "errorCode". But, as per the c7n/handler.py (line 54), the lambda function returns if it finds the errorCode in the event and therefore no action is invoked.  

Is there a easy way to override this behavior? Thanks.

**Comment by kapilt** [comment]
The error catch and skip there because there is no control plane resource change on an error. Data plane usage (like s3 put/get, or kms encrypt/decrypt) is typically a vastly differently cardinality then control plane activity which custodian is commonly used for. There isn't anything inherently at issue with that, ie. we can provide for explicit configuration to allow for error event policies, but the question would be what you want to do with such an event? For notifications, without messaging aggregation downstream, you'll potentially be sending a lot of messages to users.

**Comment by ragunathp** [comment]
Per se, it is not an issue, but preventing us to implement the mandatory compliance requirement as stated above. Our use cases cover both control & data plane cases. we are able to achieve the other data plane use cases when there is no error code (like for e.g. action/notification of cloudfront usage without https).

Though we can implement this requirement using custom lambda or cloudWatch rules, it would deviate from the other policies we have written using c7n. This may add up additional maintenance, testing & deployment overheads for those custom implementation. 
I think there will not be lot of messages sent to users, like other filter & match pattern, notifications would be sent only for the matching filters (in this case, action/notification is triggered only for filters matching specific errorMessage /errorCode ). Therefore I think there will not be lot of messages to users. I guess this the same principle for other data plane use case too.
As I am new to c7n, you may please assess the merit of this requirement and advise.

**Comment by kapilt** [comment]
contributions welcome

**Comment by kapilt** [comment]
The referenced pull request, will allow configuring the behavior of skipping of events that have err'd via configuring an environment variable for the policy. ie. setting `C7N_SKIP_ERR_EVENT=no` will satisfy this use case.
