### ISSUE TITLE
ecs-service and ecs-task resources do not support cloudtrail policies

### ISSUE THREAD

**Issue by RobMohr** [cloud-custodian/cloud-custodian#3185]
When validating a policy using cloudtrail mode on ecs-service or ecs-task resources an ERROR is returned saying "resource:ecs-service does not support cloudtrail mode policies"

**Comment by kapilt** [comment]
yeah thats an explicit safety check, resources that require a parent/container to query them need explicit support for trail events as they would otherwise need to naively query too many resources. The ids expression in a trail event policy cant express capturing both the resource id and its parent id.  what's your use case around doing a cloudtrail event policy around ecs, in particular which api calls are you  interested in?

for ecs in particular its probably going to be easier for us to just support the ecs container events, but that won't capture on ecs service.

**Comment by RobMohr** [comment]
I'm interested in CreateService and UpdateService API calls for ecs-service, and RunTask for ecs-task. I want to see if the service or task is assigned a public IP.

**Comment by thisisshi** [comment]
this _should_ be doable now as the new task arns have the cluster name embedded, we should be able to get just the task/service/container instance without getting all of the parents and all of the children
