### ISSUE TITLE
Does output-dir include minute sub-folder create feature in S3-logging?

### ISSUE THREAD

**Issue by umitseremet** [cloud-custodian/cloud-custodian#3203]
When I run my custodian policy as;

`custodian run --output-dir s3://XXXXXX custodian_ec2_snapshot.yml`

It generates some subfolders which include year/month/day/hour, but it does not include minutes folder like below path

`AmazonS3:log/XXXXXX/ec2-snapshots-test/2018/12/03/23`

the result of date command;

`Mon Dec  3 23:56:47 UTC 2018`

Because of that result if any policy runs more than one times in an hour all outputs are overwritten by the latest run outputs. If I want to keep all outputs without any lose what can I do to create an additional minute folder?

I do not want to use a that kinds of combination like below, because if you have lots of policy it is quite hard to find its name inside of S3 with that combination;

``custodian run --output-dir s3://XXXXXX/$(date +%Y-%m-%d_%H-%M-%S) custodian_ec2_snapshot.yml``

**Comment by kapilt** [comment]
so its not documented because it breaks the logs and report subcommands, but one of the changes with 8.30+ is that it is possible to customize the output directory using variable interpolation, the following are valid variables

```
            'account_id'
            'region'
            'policy_name'
            'now'
            'uuid'
```

wrt to now its a utc time stamp/datetime. formatting is per http://pyformat.info more specifically
https://pyformat.info/#datetime



ie. as an example `-s "s3://mybucket/custodian/{account_id}/{policy_name}/{now:%Y-%m-%d %H:%M}"`

**Comment by kapilt** [comment]
also for lambda policies by default affair we do a uuid expression to prevent overrides when configuring an output directory.

**Comment by umitseremet** [comment]
That format works, manipulating {policy_name} fix my problem, thanks for help;

`custodian run --output-dir s3://XXXXXX/$AWS_PROFILE/{policy_name}/$(date +%Y-%m-%d_%H-%M-%S) custodian_ec2_snapshot.yml`
