### ISSUE TITLE
How to Ensure guardduty is configured using CloudCustodian

### ISSUE THREAD

**Issue by techsami** [cloud-custodian/cloud-custodian#3316]
How to Ensure guardduty is configured using CloudCustodian

**Comment by kapilt** [comment]
Re ensure do you mean detect (filter) or configure (action)?

so we normally point folks to https://github.com/cloud-custodian/cloud-custodian/tree/master/tools/c7n_guardian for guard duty enablement, reporting, configuration re custodian support for guard duty. Its a separate cli tool uses the same account format as c7n-org.  

There is a pr that would add some notion of guard duty support directly to custodian #2628 but its been stalled because its not clear if thats adding value. I think adding at least an account filter for checking/detecting guard duty enablement definitely makes sense. 

Remediation/Enablement actions though are a bit tricky because it typically requires a multi-account handshake with multiple failure modes, which is why c7n_guardian exists as a separate tool. ie. it typically needs account root email, which afaicr is not discoverable from api minus organizations, and the handshake means role assuming into both guard duty master and target account. from a cli or lambda perspective that means custodian and a best practice on security boundary  would custodian having to be executing in the guard duty master and then role assuming into the target accounts derived from organizations, ie it feels a bit more like custom code then a typical custodian policy.. which is why c7n_guardian exists. Nutshell it requires a lot of contextual awareness of the account setup for custodian usage. c7n_guardian gets to defer that to the user and disambiguates the organizations api aspect to the config file generation. We have run c7n_guardian in a periodic lambda hooked up to organizations api for autoenablement in simpler organization setups.

Note that the c7n_guardian support predates cfn support for guard duty with stack sets as it was built right after the guard duty public announce. afaick most people today use cfn stack sets for guard duty setup today.
