### ISSUE TITLE
periodic mode, option to disable provider automatic retries on error

### ISSUE THREAD

**Issue by baptiste-s** [cloud-custodian/cloud-custodian#3454]
Hi,

on a busy account, with lots of instances, I am running a snaphost policy every days. 

Once in a while, I am getting this error : 

```
An error occurred (InternalError) when calling the CreateSnapshot operation (reached max retries: 4): An internal error has occurred: ClientError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 105, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 832, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 510, in run
return PullMode.run(self)
File "/var/task/c7n/policy.py", line 264, in run
results = a.process(resources)
File "/var/task/c7n/resources/ec2.py", line 1229, in process
raise f.exception()
ClientError: An error occurred (InternalError) when calling the CreateSnapshot operation (reached max retries: 4): An internal error has occurred
```

Looking at my snapshots, I am having 4 times more snapshot than I should have (4k instead of 1k).

**Comment by kapilt** [comment]
I'm not sure what the question is. InternalError denotes a ec2 control plane error. Custodian will retry on throttle exceptions which happen before the snapshot api machinery gets invoked (ie throttles happen on frontend of aws api machinery), unknown errors stop as in this case. Wrt to instance snapshots, its a snapshot per attached volume.

**Comment by baptiste-s** [comment]
Hi, 

thank you for your reply. 

Today my report is showing that I have 4k snapshots instead of the usual 1K. 

Looking at the lambda logs, it started over 4 times with the same error. 

do you have any idea on what can cause the error and why I have 4K snapshots ?

**Comment by kapilt** [comment]
wrt to the why on additional snapshots, doing policies in lambdas, needs to be cognizant of builtin lambda retry behavior https://docs.aws.amazon.com/lambda/latest/dg/retries-on-errors.html .. wrt to the why on the error, it sounds like the account is not healthy, if its throwing regular internal exception errors, i'd check cloudtrail to see how common this (along with rate errors) and contact your support channels about internal errors on api or app teams to reduce the bad api call behavior.

**Comment by kapilt** [comment]
i'm wondering if we should do a top level error catch on periodic mode policies to handle this to avoid the builtin lambda retries, but given a primary mechanism for monitoring lambda policies is checking against the lambda error metrics, it has some downside. we do publish a separate error metric since 0.8.33.x  so we could direct folks to that.

**Comment by kapilt** [comment]
for gcp the execution mode configuration lets one directly specify the retry behavior, not sure if this configurable directly in azure or what the retry behavior is there.

**Comment by kapilt** [comment]
added a pr that allows controlling the error catching behavior via env var, if you set

`C7N_CATCH_ERR=yes`

for the lambda, it will catch errors instead of propagating them to the lambda layer. I'm not sure if we can change the default on this safely as it has some potential impacts to error monitoring via lambda metrics, so for now its an explicit config on setting this value. 

@thisisshi any thoughts on defaulting this to `yes`?

**Comment by thisisshi** [comment]
I think defaulting to yes is probably fine for periodic, as the expected behavior is that the lambda should only run once per invoke unfortunately the retry mechanism on lambda isn't user configurable from what I can see...

Swallowing the error isn't ideal for the reason you gave (error monitoring via lambda metrics) but we do have mechanisms for capturing policy execution failures via the metrics flag-- I'm assuming that on exception catch that would be treated as a policy failure and sent to cloudwatch?

**Comment by thisisshi** [comment]
Though to be fair I don't really see a case where one would want to retry on a cloudtrail based policy either

**Comment by thisisshi** [comment]
or actually we could default to catching and send an error to the default lambda metric namespace. I _think_ that would prevent retries + preserve the error reporting behavior as the retries are done if the lambda function itself exits with an error (I'll do some testing to confirm)

**Comment by kapilt** [comment]
yeah, there's not much we can do with the default lambda metrics or retry behavior, if the user has the policy configured to push metrics, there is a separate error metric that would still be published on error.
 
wrt to a change on the default here,  dlq error watching and metrics error watching which are probably common and current practices for ops would effectively be incompatible with a switch. The flip side, is that behaviorally i can't think of a single reason, why a policy author would want the default lambda retry behavior as a default behavior across all policies.
