### ISSUE TITLE
config-rule and compliance

### ISSUE THREAD

**Issue by kabo** [cloud-custodian/cloud-custodian#3615]
I've set up a simple policy:

```yml
policies:
  - name: ensure-encryption
    mode:
      type: config-rule
      role: arn:aws:iam::1234567890:role/cloud-custodian-testing-role
    resource: s3
    filters:
      - "tag:c7n": present
    actions:
      - encryption-policy
```

It does great at ensuring any buckets tagged with `c7n` have the encryption policy.

However, when I look at the config rule in the AWS console it looks like this:
![2019-03-04_06-29](https://user-images.githubusercontent.com/357601/53714610-f743e200-3eb3-11e9-8f39-973f5c8ec97d.png)

And if I have a look at the CloudWatch log for the lambda it says

```
[INFO]		Filtering resources with [<c7n.filters.core.ValueFilter object at 0x7efe9deb69e8>]
[DEBUG]		applied filter <c7n.filters.core.ValueFilter object at 0x7efe9deb69e8> 1->1
[DEBUG]		Filtered from 1 to 1 s3
[INFO]		Filtered resources 1
[DEBUG]		Storing output with <LogFile file:///tmp/87488a05-04f7-4df3-be7c-002679b83541/ensure-encryption/custodian-run.log>
[DEBUG]		metric:ResourceCount Count:1 policy:ensure-encryption restype:s3 scope:policy
[INFO]		Invoking actions [<c7n.resources.s3.EncryptionRequiredPolicy object at 0x7efe9deb6940>]
[INFO]		policy: ensure-encryption invoking action: encryptionrequiredpolicy resources: 1
[DEBUG]		Bucket:c7n-test-calle-3 Found extant encrypt policy
[DEBUG]		metric:ApiCalls Count:0 policy:ensure-encryption restype:s3
[INFO]		found resources:1 match-compliant:False
```

It seems to me that even though the lambda fixes the encryption policy it reports back to AWS Config that the resource is noncompliant. Which IMHO is a bug.

**Comment by kapilt** [comment]
custodian config rules by default mark resources which match their filters as non compliant. the bug here is that your policy takes actions on the resource which your not filtering for, ie.. an ideal policy is idempotent and convergent on state. ie. if i run this policy twice, it will simply modify the resource twice. two changes to the policy for example that would resolve your issue would be to tag the resource in actions, and filter for that, or filter for the presence of the encryption policy statement.

if you have suggestions on alternatives, please work through/provide an example of desired behavior for both the compliant and non compliant evaluation scenarios.

**Comment by kabo** [comment]
OK, that is not what I was expecting after reading the documentation.
https://cloudcustodian.io/docs/policy/lambda.html#config-rules

Perhaps the documentation should filter out stopped instances, and explain why?

**Comment by kapilt** [comment]
good point, the docs should be better on this. if your at pycon 2019 this year, we're doing a sprint after the conference and docs are one of the main focus topics.
