### ISSUE TITLE
Support GCP resources without list actions but contain get action

### ISSUE THREAD

**Issue by mediapills** [cloud-custodian/cloud-custodian#3822]
There are resources without list actions but contain get action. The current implementation does not allow implement only to get action but application use it for audit.

**Solution:**

In the case of Kubernetes, there is projects.zones and projects.locations. To cover this functionality new "kubernetes-project-zone" and "kubernetes-project-location" resources have been implemented. This resources will show NotImplementedError during access to list action and ServerConfig object during "getServerConfig" action. New functionality implemented in KubernatesProjectZones and KubernatesProjectLocation classes.

**Example:**
```python
@resources.register('kubernetes-project-zone')
class KubernatesProjectZones(QueryResourceManager):

    def resources(self, query=None):
        raise NotImplementedError(
            'Action list not implemented for resource projects.zones'
        )

    class resource_type(TypeInfo):
        service = 'container'
        version = 'v1'
        component = 'projects.zones'

        @staticmethod
        def get(client, resource_info):
            return client.execute_query(
                'getServerconfig', verb_arguments={
                    'projectId': resource_info['project_id'],
                    'zone': resource_info['zone']})
```

**Resources list**

*Kubernetes Engine*

- [projects.zones](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones)
- [projects.locations](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations)

*Tag Manager*

- [versions](https://developers.google.com/tag-manager/api/v2/reference/accounts/containers/versions)
- [folders.move_folders](https://developers.google.com/tag-manager/api/v1/reference/accounts/containers/move_folders)
- [environments.reauthorize_environments](https://developers.google.com/tag-manager/api/v1/reference/accounts/containers/reauthorize_environments)
- [services.consumers](https://cloud.google.com/service-infrastructure/docs/service-management/reference/rest/v1/services.consumers)

*Cloud Datastore*

- [projects](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects)
- [projects.serviceAccount](https://cloud.google.com/storage/docs/json_api/v1/projects/serviceAccount)
- [channels](https://cloud.google.com/storage/docs/json_api/v1/channels)
- [projects.templates](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.templates)
- [projects.locations.templates](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.templates)

*Cloud Spanner*

- [projects.instances.databases](https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances.databases)
- [projects.instances](https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instances)

*App Engine*

- [apps](https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps)

*Cloud Resource Manager*

- [organizations](https://cloud.google.com/resource-manager/reference/rest/v1/organizations)

More implementation details info you can find [here](https://github.com/mediapills/cloud-custodian/pull/19).

PS. *NotImplementedError* as it is error for abstract not implemented functionality and it is derived from *RuntimeError* can be replaced by *RuntimeError*.

**Comment by kapilt** [comment]
several of these resources don't make sense, ie locations and zones are basically static metadata. app engine is also special in a different way its always a zero or one return set, so can be implemented with get, since app engine instance id == project id. organizations uses search for list, etc. projects datastore stuff doesn't make sense in a custodian usage, its about app integration not management. lets target resources with actual concrete use cases then trying to reflex everything in the gcp api into custodian for a checkbox.

**Comment by jondavidi** [comment]
@alexkarpitski some observations on my part:

- I'm uncomfortable with using `NotImplementedError` because per official Python docs, it's supposed to be reserved for a base class that expects a sub-class to implement it

- building on that, I'm also uncomfortable with the notion of breaking fundamental sub-classing principles by inheriting from a base class and not implementing one of its methods. By doing that it's not actually a proper subclass, and if someone tried to substitute it for an instance of the base class it certain places, it would break because of this.

I think the approach needs to be re-evaluated to find an alternative to a partial sub-classing. Maybe that means making a new class that contains an instance of the current targeted base class (e.g. using composition instead of inheritance).

@thisisshi I would be curious to hear your thoughts on this, particularly to where even if this worked for just the audit mode, if it would break other areas of functionality outside of the audit mode that expect this for initialization purposes of a resource or something etc.

**Comment by mediapills** [comment]
@kapilt during conversation suggest implementing get resources without list action in a list way and use ecs.py as an example.
