### ISSUE TITLE
find unused subnet

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#390]
and action for delete, subnets report their used/total so this should be easy.

**Comment by andrewalexander** [comment]
Despite the console showing the available, the APIs actually only return the available IPs. We can easily calculate those numbers by looking at the CIDR though and doing the conversion, keeping in mind that Amazon [reserves 5 IP addresses in each subnet](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html#VPC_Sizing).  

Describe call:
```
{
    "Subnets": [
        {
            "VpcId": "vpc-REMOVED",
            "Tags": [
                {
                    "Value": "MY-Sample-Subnet",
                    "Key": "Name"
                }
            ],
            "CidrBlock": "10.20.0.0/24",
            "MapPublicIpOnLaunch": false,
            "DefaultForAz": false,
            "State": "available",
            "AvailabilityZone": "us-east-1b",
            "SubnetId": "subnet-REMOVED",
            "AvailableIpAddressCount": 251
        }
    ]
}
```
We see 10.20.0.0/24, so we know /24 -> 256 IP Addresses. 256-5 reserved = 251. So the above would be an unused subnet.

**Comment by kapilt** [comment]
that looks pretty good, the alternative is an exhaustive search through all resources that could be vpc attached, which may actually be what we need to do, since some of those resources (aka lambda) are transient in usage.

**Comment by skurfer** [comment]
I’ve spent some time looking into this and I’m not sure about the feasibility. If we’re going to delete a subnet, we need to be 100% sure it’s “unused”.

As you pointed out, we probably need to search through resources rather than rely on the available number alone, but which resources? There’s a list of [related resources][1] in the docs, but it doesn’t include the one example you cited (Lambda) which makes me wonder what else might be missing.

Querying all of those resources individually would require a decent amount of effort, and I’m not sure it will get us to “100% sure”. Do you think it’s worth it?

[1]: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Introduction.html#related-services
