### ISSUE TITLE
Azure - Cost Efficient Policy Scaling Options (hosting, functions)

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4121]
# Summary

Currently Custodian can be deployed on Azure with hosted Azure Functions with three underlying infrastructure options

* Consumption (serverless)
* App Service Plan (dedicated vm)
* App Service Environment (dedicated vm and app service infrastructure)

With our current implementation only **consumption** scales well without cost/management issues.  Dedicated VMs fail to scale well as each policy we deploy requires a Debian Stretch docker image which exhausts VM memory quickly.

We have found most large customers are unwilling to approve **consumption** functions due to security concerns related to their lack of private networking.

![image](https://user-images.githubusercontent.com/4087345/59198089-c674e800-8b47-11e9-80b4-8187599177cd.png)

# Solutions

Below are discussions of potential improvements of varying costs

## (A) Move to Alpine Images
**Cost**: Small
**Improvement**: Requires measurement, estimated 2x density

The functions team already maintains Alpine functions dockerfiles for Python, however they may not be publishing them to dockerhub.  

https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/alpine/amd64/python.Dockerfile

There are a few options on how to deal with it not being published, they have a tracking bug with no response at:

https://github.com/Azure/azure-functions-docker/issues/79

We can:
* Add this to a public registry ourselves
* Ask PG to get it published
* ...?

## (B) Multiples Policies per App
**Cost**: Medium
**Improvement**:  Estimated 100x to 10000x 

A **Function App** represents a docker container instance and a **Function** represents a Python instance and configuration pair.  

Currently we deploy 1:1:1 Functions/Function Apps/Policies (with exceptions for management group support) because a Function App is the smallest unit of deployment and our only boundary for isolation of Python dependencies.  

We can support **deploying multiple policies into a single Function App**.

#### (1) Support an explicit deployment option/path that will deploy multiple Functions into a single Function App.   
* The entire function app is overwritten on each deployment.  
* Requires some devops process to manage deployment as it needs to be done centrally
* A separate Python tool to deploy as the concept doesn't fit into the CLI
* This tool can also be wrapped as Azure Devops Task

#### (2) Full redesign of serverless implementation such that policies are decoupled from functions
  * One Function in one App, many policies
  * Function is deployed with a configuration entry pointing to a storage container instead of a policy file
  * Function has both Timer and Queue triggers
  * On Timer trigger entrypoint enumerates policy files in storage container and updates cache, then executes any appropriate periodic policies
  * On Queue trigger entrypoint  executes policies which match event topic
  * Deployment of new policies means upload a blob, and potentially adding event hub topics
  * We increase event hub scalability due to having a single queue and no duplicate event subscriptions
  
## (C) Support Docker/K8s Function Output To Disk
**Cost**: Small
**Improvement**:  Varies

Azure functions runtime and CLI already support generating docker images and config to run in Docker or K8s instead of hosted Functions.  These work well and provide the customer with flexibility to run however they would like (ACI, on-premise, existing AKS).

This is easy to implement, we just generate our functions folder as normal, but instead of downloading wheels, compressing, and deploying the folder we simply copy in a static `dockerfile` and config.   The `dockerfile` has a multi-stage build which will handle all the python dependencies automatically when the customer builds it.   

We would need some config or command line option to trigger this mode.

**Comment by kapilt** [comment]
the primary issue with consumption plans has historically been they end up putting an http end point on the internet for each function, which is pretty verbotten imo wrt to security controls. historically this has been due to a lack of a proper data plane api (invoke function) within the api which meant http invokes. my understanding was that this capability does exist now and in conjunction with removing the http endpoint should remove most security concerns given education on the current state of functions, but comes with the baggage of combatting/reducating all the historical knowledge/prejudices. The real question for this to be viable is to ensure that our event sources are using it (aka grid). The whole notion of provisioning and managing servers is kinda of baroque wrt to serverless/faas.. perhaps keda is useful in this context... perhaps not .. https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda

a) its unclear why this is beneficial, can you provide some additional context on what problem it addresses. the custodian upstream docker images (ie in this repo) are already optmized for size (<500mb). most of the size pain afaicr was test data and azure dep graph. alpine brings it with its own set of headaches and compatibility concerns wrt to musl / kernel compatibility which has bitten folks before, especially if your host os is rev'ing kernels fast. its possible we might be able to get some additional shrinkage with a multi-stage build.

b) an option to explicitly set a function app name seems reasonable. the issue is that we'll have to grow better gc capabilities. the other providers allow for both add/remove of functions, which can then be used by tools like mugc.py for removal.

c) i'd like to understand this a bit more. it sounds like a separate entry point thats setups as a queue processing daemon? but then what per se does it have to do with azure functions... ie. how is this different then just run a container, and avoid the failure of azure functions to address use cases and just remove its complexity/runtime from the equation entirely.

**Comment by stefangordon** [comment]
@kapilt  Yep all invocations happen without the need for HTTP Endpoints now and the service offers inbound IP filtering.  IP Spoofing is a valid concern but if you just block everything you are probably OK.

A) The problem is that on a $60/month App Service Plan we can only run ~10 policies due to the available RAM.  So for a customer we were discussing this with last week the cost to run Custodian may have been $6000/month (they do not approve Consumption plans).    Alpine has a smaller memory footprint which gives you a bit higher container to VM density.   Maybe not enough to be worth trouble, but if Functions team supports the image already and it works then it may be an easy win.  These are the Azure Functions Runtime images (with Node, DotNet, etc), their default one is very fat in terms of loaded kernel modules to increase compatibility.

C) So you are still using the Functions Runtime container with its built-in overhead like periodic and event triggers, logging, etc.   You are just running it yourself instead of sticking it in the hosted platform.  The goal of the functions team here was to provide mobility between Azure Functions and Kubernetes.  Certainly we could just write our own scripts/containers to support handling the CRON/periodic and event modes, but you get it for free this way.

When we upload to hosted functions we just let them use the default pre-build container and they mount our files, but we can also just `docker build` ourselves and get an image with our files in it that works outside of hosted functions (e.g. listens for triggers and executes).
