### ISSUE TITLE
Azure - Support MSI for App Service Plans (not consumption)

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4122]
MSI Auth should work for non-consumption Azure Functions today if we make some minor fixes.

We have MSI implemented (#3168) for people just running ad-hoc on Azure VM's, it works based on environment variables.   However we don't let you deploy to Azure Functions with MSI.   

We need to update the way we write our config file to pass the MSI info in, and update session.py to take the MSI path based on the config.

Consumption probably doesn't support this today, but it will work the same so this implementation should light that up as the features come online.

Also please update docs appropriately to explain MSI as auth option for functions.

**Comment by kapilt** [comment]
msi without CPI (customer provided identity) seems unclear how it can be used usefully. ie an identity/principal per function means they get what permissions by default? nothing? so then the deployed function doesn't work? or the custodian executing principal needs permission to configure iam policies on the msi prinicipal? thats generally now how must orgs run. this notion of a resource with an resource specific identity does really mesh well with common usage, because the resource is half provisioned effectively till adminstrator comes in to setup the policies for the identity. much better is customer provided identity, which allows pre-provisioning of the principals and its policies, and then just referencing/associating it to the resources. it also decreases the number of principals under management.

**Comment by stefangordon** [comment]
Yeah the intent here is to support both "System Assigned" and "User Assigned" which we support via environment variables today.  User Assigned would be the CPI you are referencing - it works basically like a service but the credentials come through the secure MSI mechanism instead of being deployed in a config file.  The GUID to identify the identity still has to be in the config.

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-cli-windows-vm#user-assigned-managed-identity

System assigned is hard to manage at any scale as you mention, so its probably best used for small scenarios or  potentially as part of a keyvault auth strategy with #4125
