### ISSUE TITLE
AWS - support custom Cloudwatch Events

### ISSUE THREAD

**Issue by xgarcias** [cloud-custodian/cloud-custodian#4273]
AFAIK custodian only supports a predefined list of cloudwatch events. This is cloudtrail, guard-duty, etc. See the link below

https://github.com/cloud-custodian/cloud-custodian/blob/0.8.44.1/c7n/mu.py#L1000

Since cloudwatch events supports sending custom events, this feature could let us send kubernetes audit logs, auditd (in json), etc  to Cloud Custodian, allowing us to use it as a single alerting engine across the organization.

I am not sure if this new feature requires big changes in the code base.

Resources:

-  https://aws.amazon.com/blogs/security/how-to-use-amazon-cloudwatch-events-to-monitor-application-health/

-  https://boto3.amazonaws.com/v1/documentation/api/latest/guide/cw-example-events.html#id5

**Comment by kapilt** [comment]
its a more question of should rather than can, the actual amount of work isn't large to support subscribing to arbitrary events. However in general custodian isn't a general purpose event processor, it subscribes events to trigger policies on resources which can then take advantage of vocabularies of filters/actions. for generic events there wouldn't be any vocabularies minus generic ones, and its unclear if those are going to be useful enough vs a dedicated event stream processor project that would also handle event archiving, replay, event window analysis, etc.

**Comment by xgarcias** [comment]
Closing the issue.
