### ISSUE TITLE
Usage of timeout parameter in old version

### ISSUE THREAD

**Issue by techsami** [cloud-custodian/cloud-custodian#4293]
Hi, I am using custodian version: 0.8.32.1 which is currently customised as per environment and cannot be upgraded very easily. We need to build a check if defined mandatory Tags are present when DynamoDB is created. For this we are catching the CreateTable event and check the filter for tags but it is failing to check the tags as for DynamoDB, tags takes time to create which custodian cant wait. I come across the parameter timeout but seems this parameter is not working in my current version of custodian. Can you please suggest an alternative? Can I copy certain files from latest version of custodian to my current version in order to make this parameter workable? What are the files we can copy from the latest version as an alternative of version upgrade? Probably we can limit this custom upgrade only for DynamoDB to make the solution workable.

**Comment by kapilt** [comment]
so you've forked custodian and want the communities help in maintaining your fork? sorry thats not a useful use of anyone's time including your own. I suggest you figure out how to not be on a fork, perhaps even contribute whatever 'customized' bits you felt were needed. wrt to timeout thats a lambda function timeout, not a random sleep insertion. wrt to tags on newly created resources, I suggest you not try to have a race condition, and either use a periodic policy or config rule policy instead of trail on create.
