### ISSUE TITLE
azure - filter CosmosDB collections based on parent properties

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4390]
Would be great to add some filtering on parent properties, e.g. 'CosmosDB collections from Cosmos DBs with certain tags'

**Comment by stefangordon** [comment]
I think this may just be a small enhancements on the child resource query to make sure we include access to the parent as needed.  Currently we may just include the parent ID or other specified fields rather than a flag to fully set `c7n:parent` to the resource dictionary.

Tasks:
- Investigate solution for the child resource
- Propose design (in this thread)
- Implement
