### ISSUE TITLE
Support pushing AWS Config rules to AWS Organization

### ISSUE THREAD

**Issue by jakauppila** [cloud-custodian/cloud-custodian#4433]
AWS announced the ability to push custom Config rules to all accounts within an Organization on July 9:

https://aws.amazon.com/about-aws/whats-new/2019/07/aws-config-now-enables-you-to-provision-config-rules-across-all-aws-accounts-in-your-organization/

It would be awesome if Cloud Custodian supported this to simplify pushing policies to accounts.

**Comment by kapilt** [comment]
running c7n-org can effect fast simple deployment across an organization of config rules and lambdas.

custodian also supports centralized lambda setups. 

i'm not entirely sure the value chain here, it looks like primarily its because they would be immutable in the target account, buts fairly easily achieved via iam as well.
