### ISSUE TITLE
gcp - vpc service - work with organizations

### ISSUE THREAD

**Issue by evhenyshaliov** [cloud-custodian/cloud-custodian#4547]
We implemented a feature that allows to work with VPC service. 
The feature is useful in terms of audit security, update security policies in an organization etc. Some use cases are available in the branch in rst file.
The service doesn't work with gcp project. It works with organizations. So we propose to add ability to use organizations using query param.

The PR is https://github.com/mediapills/cloud-custodian/pull/72.

@kapilt please let us know if the service can be added in the current state.

**Comment by aleonidex** [comment]
@kapilt looking forward your thoughts on the matter. This (usage of organizations) seems like a kind of precedent for Custodian, yet reasonable. Other suggestions surely welcome.

**Comment by kapilt** [comment]
it seems to suffer from the same over use of resources to represent nested values instead of using and filters and actions on the parent, as is it leads to a gluttony of resources that people can't use which is not what we want and has been pointed out at numerous times in previous reviews. However at least directionally it has some utility for use by custodian users. wrt to organizations based functionality thats fine.

**Comment by kapilt** [comment]
I added some feedback there, but there really seems to be some fundamental misunderstandings on the project goals wrt to the why  thats persistent across the gcp contributions, the intent is to simplify and enable managing environments, not simply be an equivalent to execute shell scripts. ie. using project ids when applying perimeters at scale simply does not work, so figuring out how to simplify and be useful to end users means understanding that. again part of this stems from contributors not using what their contributing. ie. support symbolic project names and folder hierarchies to simplify the management application of perimeters and policies.
