### ISSUE TITLE
Lambda mode - region:all causes function to exit without error - "Skipping policy:{policy} target-region:all current-region:us-east-1"

### ISSUE THREAD

**Issue by anthonybgale** [cloud-custodian/cloud-custodian#4655]
Given a policy containing `region: all` in its definition, running in Lambda mode,  https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/policy.py#L323 self.policy.region evaluates to 'all' and the policy is skipped.

**Comment by kapilt** [comment]
interesting, I'm a little unclear on why a policy would have region: all. policy specified regions are used to limit regions, ie the default without specifying region on a policy is all. its the cli execution that determines active regions, the policy spec just serves to filter those.

**Comment by anthonybgale** [comment]
My mistake. I'm not sure where I got the idea that all was a valid region. I wonder if it is useful to allow this to be explicitly specified.

**Comment by kapilt** [comment]
we do allow --region=all on the cli for c7n and c7n-org, and its not prohibited by the policy json schema so its understandable getting there, isn't meaningful to do per se. I don't think we have compatibility constraints here since it doesn't putting in `all` value here. there's some discussion separately on refactoring policy execution conditions to allow richer definitions. we are currently retaining this key/value for multi-cloud work though at the moment azure and gcp operate multi-region always (=all).
