### ISSUE TITLE
azure - monitor / sentinel integration

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4751]
Many Azure customers now use Azure Monitor as their primary window into non-compliant resources.  Sentinel is a new component of that https://azure.microsoft.com/en-us/services/azure-sentinel which is the recommended approach for custom alerts now. 

We need research/design on how we can expose custodian output here in a nice way.

I believe the approach is basically:

1) Custodian writes to supported data stores (App insights)
2) Monitor/Sentinel/Log Analytics have queries to alert based on those data stores

But the implementation has lots of options (Should we have an action to write structured app insights events about resources? Can we build some pre-configured Azure Monitor or Sentinel configuration to deploy for users?)

This link talks about old custom alert experience going away:
https://docs.microsoft.com/en-us/azure/security-center/security-center-features-retirement-july2019#custom-alert-rules-preview

**Comment by aluong** [comment]
I think we should decouple the Azure Monitor and the Sentinel integration. 
Adding a Sentinel action (#4828) is a good idea, because Custodian can be another data source for security issues. Ex: someone is opening up ports in a production NSG. However, other policies for Custodian may not be relevant to be surface here. Ex: cost management or maintenance.
