### ISSUE TITLE
allow cloud-custodian --log-group to use arn for cross-region/account logging.

### ISSUE THREAD

**Issue by gileshinchcliff** [cloud-custodian/cloud-custodian#4795]
When running c7n with an assume-role/region passed in, it utilises the local region for creating aws log-groups/streams. 

This is great default functionality but when managing all regions in 10s of accounts it becomes painful. Would it be possible to pass in an arn for the centralised log-group to avoid having to manage multiple of each. 

So rather than: `--log-group=cloud_custodian/<account>/<region>`
it would also accept `--log-group-arn=arn:aws:logs:<region>:<account>:log-group:cloud_custodian`

If there's a will to approve and merge this, I'd be happy to have a crack at coding it, otherwise I guess the alternative is to wrap c7n in something which manages logging outside of it, or creating more infrastructure for centralising the logs, which we do have but seems overkill for this use case.

Anyhow, let me know your thoughts.

**Comment by kapilt** [comment]
for metrics we support this sort of targeting aggregation setup, we don't at the moment for logs. it seems like a useful addition, its not quite arn targeting because we also support other clouds here, its via url  so perhaps `aws://master/log_group_name?region=us-east-1`. note will likely need to do some work here to separate out all the policies, accounts, regions into separate streams or log groups (ie perhaps in some cases a log group prefix, to make isolating to a particular environment easy.

 so it would be good to understand what the log group / stream destination use case is.

also note we also distribute tools/c7n_logexporter which allows streaming all those log groups back to firehose for aggregation.

**Comment by gileshinchcliff** [comment]
Yeah I saw the logexporter, again it just seemed a bit overkill for our needs. I think I'll probably split this into 2 pieces. Initially cross region, to allow sending all logs to one region within an account (to then be shipped to a central account from whatever mechanism exists). 
Good shout on the url, I'll take a look at the metrics aggregation and see if I can replicate the same logic for logs.

**Comment by kapilt** [comment]
what i'm looking for is a examples of what the stream destination changes to in the presence of these options. ie if you aggregate to one region, does the execution there get a different stream to distinguish by region? same for multi-account aggregation. maybe we need to support user supplied templating for the log group name and stream name.

**Comment by gileshinchcliff** [comment]
I guess my view would be that we'd add additional streams per region/account. So the streams would look like:
```region/policyname```
With account it would be:
```account/region/policyname```

That way it would be easy(ish) to search for the right info, alternatively you could add some metadata into the log itself, but that would require json logging which I believe isn't supported yet and only be useful once it was ingested by some other log aggregation system (elk etc).

**Comment by kapilt** [comment]
thanks, that sounds reasonable re example, wrt to json log output, its definitely of interest, there's some open questions wrt to lambda at the moment, since it drops text records into the output stream independent of the application.

**Comment by gileshinchcliff** [comment]
it would be dependant on this ticket though right? https://github.com/cloud-custodian/cloud-custodian/issues/282
