### ISSUE TITLE
Dump the resources or policy execution data to a centralised location

### ISSUE THREAD

**Issue by jksgit** [cloud-custodian/cloud-custodian#4946]
These policies are running as lambda in all accounts and currently implemented email notification using c7n_mailer. I dont want to dump the data to cloudwatch metrics, instead can I send it to any webhook like prometheus, splunk( saw an integration already) etc?

Please provide any documentation as well and dont close this after your reply.

_Originally posted by @kapilt in https://github.com/cloud-custodian/cloud-custodian/issues/4938#issuecomment-541066980_

**Comment by kapilt** [comment]
instead of filing a duplicate new issue you can comment on the original. we generally close question issues that are considered answered. 

you can add something to your policy as an action ie. use the web hook action or invoke-lambda or the invoke-sfn to send the data to your custom code.

you can also use the sns transport for notify to enable a pub/sub mechanism, with a mailer sqs on side, and custom code on the other, or you can configure the mailer to send directly to Splunk collector.

or per the previous issue you can store in object storage (s3) by providing an -s s3://bucket/prefix output path.
