### ISSUE TITLE
Question: Can AWS actions invoke-lambda/sfn invoke Lambda/Step Function in a different account?

### ISSUE THREAD

**Issue by bb1314** [cloud-custodian/cloud-custodian#5009]
I deployed an EC2 instance in account A. I'm running Custodian remotely against account B from this EC2 instance in account A using **--assume** to assume into an IAM role in account B. My my policy's action is **invoke-lambda** or **invoke-sfn**, is my only option to create the Lambda Function or Step Function in account B? Is there a way that I can keep the Lambda Function or Step Function in account A, or even in a completely different account C?

**Comment by kapilt** [comment]
no cross-account invoke isn't really supported. technically it would work for son if account B's iam role had such permission and you gave a fully qualified arn.

**Comment by kapilt** [comment]
its a one liner to use c7n-org run-script to deploy a lambda across accounts and regions. so the ops overhead is mostly imagine. I assume your already doing the ops excellence of cross region resiliency which requires dealing with multiple copies anyways. additionally as I said you can enable this out of band by having function in A trust role in B for the invoke.

re community, please note that you represent an organization that is not contributing, and has been actively working to find ways not to contribute (this issue, plugins issue). which doesn't bother me, as much as the organization has also been actively detrimental to the community and project. I'll have more patience if you lead with contribution, instead of continued questions on how to avoid it.

**Comment by bb1314** [comment]
Your suggestion on providing the full arn of the Lambda Function name worked! I just needed to explicitly add permission to the Lambda Function to allow other account(s), service(s), IAM arn(s) to invoke the Lambda Function. Thanks a bunch @kapilt !

**Comment by upeskartik** [comment]
Hey, can you share a code snippet to do that, or any link?
