### ISSUE TITLE
How to extend cloud custodian with custom filters ?

### ISSUE THREAD

**Issue by rjpereira** [cloud-custodian/cloud-custodian#5031]
I've seen a couple of times this question asked here,  but in all the cases a solution was given using existing filters or workarounds.
My use case is that wanted to extend cloud custodian with extra account filters, that allowed to implement security controls from our corporate policies. Policies around individual resources are useful for many things, but when translating corporate controls they sometimes need to have custom logic against multiple resources or even cross-check data against other systems (e.g. check that VPC CIDR ranges, are properly registered in the corporate IPAM).
From source code inspection I see that it should be as simple as @filters.register() over FilterRegistry('aws.account.filters')

(Now that I read this can you check page https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/account.py ? I read:

filters = FilterRegistry('aws.account.actions').   <---- aren't they switched ??
actions = ActionRegistry('aws.account.filters')

??? )

Coming back to my question: I understand what I'd have to do, but not sure where to "plug in" the load of my files into the general framework.... How could my classes also be included in the "zip" of lambda deployment ?

Thanks in advance for all the help you can provide.

**Comment by kapilt** [comment]
in general the custodian philosophy is to have filters in the core that enable them to be parameterized and composited/aggregated to express business policies. its better to have integrations out of band then trying to incorporate them into the custodian runtime. many of the things your referencing are enabled via the value filter's value_from syntax which allows referencing external data dictionaries in s3 or urls as vocabularies. this enables data integrations with external systems without tight coupling and also us via s3, to decouple from those external systems availability. 

for actions we support sending data feeds via notify action, as well invoking lambdas, step functions, and web hooks.

the filter/action registry for account.py you noted is a minor bug, the actual classes both derive from a registry base which has the core functionality, which is why this hasn't been an issue. I'll put up a pr to clean that up.

wrt to the specific example check vpc cidr, thats supported with existing value filter .. value_type: cidr for ip network comparisons using cidr math. wrt to registration in ipam, dump that list to a json file in s3, and use value_from to compare to the vpc. our gitter chat is a good place to ask questions if you need help translating business reqs to policies.
