### ISSUE TITLE
Correct maid_offhour and maid_onhour tag value on RDS

### ISSUE THREAD

**Issue by pricy** [cloud-custodian/cloud-custodian#5194]
Hello,

Not sure if this is a bug on the RDS but the the following tags work on EC2 but not RDS due to unsupported characters. 

 maid_offhours  off=(M-F,22);tz=est     
 maid_onhours   on=(M-F,6);tz=est

I also noticed the following classes are missing in RDS but are available in EC2.

https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/ec2.py

class InstanceOffHour(OffHour, StateTransitionFilter):
    """Custodian OffHour filter

@filters.register('onhour')
class InstanceOnHour(OnHour, StateTransitionFilter):

How best can I implement the same schedule on RDS instance?

**Comment by kapilt** [comment]
I'd suggest two things, a) talk to your account manager about a request for the service team to increase the allowed tag values. 2) due to the restricted tag value character set for rds, the workaround most commonly done in custodian is to have a set of policies for an enumeration/set of common offhours (weekends, 9-5 weekdays, etc), and then have the rds instances/clusters opt in to them via tag.

**Comment by kapilt** [comment]
and yes offhour/onhour filters are supported in rds (see reference docs or cli interactive help `custodian schema rds.filters.offhour`), albeit the with the service imposed tag value restriction.

**Comment by pricy** [comment]
Thanks Kapil. Appreciate the quick response.
