### ISSUE TITLE
CW rule event bus configuration

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#5234]
Does it make sense to make EventBusName also a configuration item for CW rules tied to `mode: cloudtrail` policies. As of now, it default to `EventBusName: default` as per the boto docs. Making it configurable can allow the user to configure it to something specific, else it would default to an empty string .

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/events.html#EventBridge.Client.put_rule

**Comment by kapilt** [comment]
i think this just adds complexity without a use case/value chain at the moment. ie. it makes custodian harder to setup rather than easier, and i haven't seen an actual use case for it. the policy conditions work will enable doing conditional execution bits easier and more directly expressed rather than trying to keep a mapping of event buses and policies on a global basis figured out.

**Comment by PratMis** [comment]
Got it, thanks!

**Comment by riyaz-ali** [comment]
We came across a use case internally where we were pushing events from child accounts in an organisation unit into a non-default event bus in our primary account. 

We couldn't use the default bus in the primary account as that would cause the policies to be applied to the primary account as well and neither could we use `c7n-org` because the nature of child account registration was dynamic.

So, I ended up [implementing this](https://github.com/cldcvr/cloud-custodian/pull/1) .. would love to submit it upstream if you guys are still considering this ticket or maybe future visitors could consider applying [this patch](https://patch-diff.githubusercontent.com/raw/cldcvr/cloud-custodian/pull/1.diff)

Would still love to get feedback on code / advise on how else we could've solved this without having to add an additional parameter

**Comment by gelouko** [comment]
@kapilt we have #2005 that allows someone to run cross-account actions within a centralized account, and some people are using that alongside an event forwarder to forward specific events to the default event bus because of the limitation pointed by the issue.
It isn't a big problem, but it makes necessary at least **2 accounts to setup Cloud Custodian** that way (as it's not possible to forward rules to an event bus in the same account)
There is one limitation factor here: the lambda parallel execution limit (soft: 1000 execs/s), but much less-likely to reach the high cardinality resources runtime problem

So, I guess at least making it clear that this architecture is possible in the docs would be a good thing, wdyt? And adding the event-bus parameter would be a plus, as it enables this architecture within just 1 account.

**Comment by gelouko** [comment]
@kapilt we have #2005 that allows someone to run cross-account actions within a centralized account, and some people are using that alongside an event forwarder to forward specific events to the default event bus because of the limitation pointed by the issue.

So, I guess at least making it clear that the event forwarding architecture is possible in the docs would be a good thing, wdyt?

**Comment by raymyers** [comment]
I also could use this, with periodic lambdas running in a central account we run into an EventBridge rule limit (even after increasing quota).

Seems like if it continued to use the "default" event bus unless an alternate is specified then it wouldn't make anything harder. Let me know if I can help with this.
