### ISSUE TITLE
Possibility to extend cloud-custodian by custom functions

### ISSUE THREAD

**Issue by KVInventoR** [cloud-custodian/cloud-custodian#5303]
Hi All

I would like to have my custom extension inside cloud custodian to have more detailed report to process additional informations  after filters.
My thought  was about calling custom python functions inside action setting to retrieve additional data and include result if this function to general data, before send report to sqs

In my case I tried to run lambda-invoke, but it's not working as I expected.
Is it possible to implement this staff?
it's something like ansible python plugins which let you possibility to extend functionality by custom code.

**Comment by kapilt** [comment]
can you give a concrete example? is it something thats worth contributing to custodian in a generalized form? we had custom plugins support (specifically to support private preview services), but we've walked that back as people were using it for other things, which caused them more problems in the long run (ie. couldn't upgrade installations), as well as causing slow startup times (setuptools entry point scanning is fairly  slow). in general we want to encourage contributions upstream, rather than a bunch of custom extensions.  whats not working with invoke lambda?
