### ISSUE TITLE
Style Consistency 

### ISSUE THREAD

**Issue by CMeza99** [cloud-custodian/cloud-custodian#5529]
I would like a consistent style across the codebase. Some inconsistencies include mixing single and double quotes, f-string/format/%, import order, etc.

If the maintainers are open to it I would like to use `isort`, `black`, and `flynt` to make things consistent. I can even add tests to tox for this.

**Comment by kapilt** [comment]
I've thought about it, but not right now, its just line noise on history, breaks every extant pr, and raises the bar on contribution, and provides no significant value. consistency is a hobgoblin.

**Comment by kentnsw** [comment]
@kapilt  @ajkerrigan  I know introducing a code format tool at this point is very painful, especially for people who are working on a large pr. But it's the right thing to do. The bar has been raised by flake8, and now it's time to provide a ladder.

No format tool means everyone who works on the code has to pay the price. You may find lots of pr got commits like 'pass lint'. Please understand how much time they had wasted and will have to continue wasting on finding out lint errors and then manually fixing them.

If I were in your position, I would format the code piece by piece. A few months pains gain a few years ease.

**Comment by ajkerrigan** [comment]
@kentnsw - comments on a closed issue are likely to be lost, but this point is important as we work to make the contributor path clearer and friendlier.

It's worth pointing out that your point and @kapilt 's are not completely at odds. If the goal is reducing contributor friction during PRs, one approach might be making local linting more well-defined and automated (via [pre-commit](https://pre-commit.com/) for example). That way you'd hit lint violations locally and not have the tedious "pass lint" commits you mentioned, and that might pave the way for incrementally applying some auto-formatting.

Running black across the whole codebase in the name of consistency is a much bigger change. There are good objections to that, and _if_ it happened I would expect it to be after smaller steps.

**Comment by kentnsw** [comment]
@ajkerrigan  Sorry about that, because I don't want to create a new duplicated issue. Please let me know what's the desired approach.
Local linting is a good point, but still not ideal. Linting all code takes time, and once errors are found, we'll have to fix them manually, that takes time too.

Again, back to my suggestion, compared to the extant PRs, a more important (and could be much worse) impact is to those 1.1k forks. Once the upstream `master` was reformatted, how could the changes be easily merged? To answer that question,  please take a look at the PR https://github.com/newscorp-ghfb/cloud-custodian/pull/41 -- merging cloud-custodian/master to my fork that both have been `blacked`. Yes, there are some conflicts that can't be auto merged. But if look into those conflicts, you'll find out that they are much easier to be solved than imagine. I can solve it in a few minutes with high confidence.

Cloud Custodian is one of the best in its area, it will have years to go. From a long-term perspective, it's worth doing it.

**Comment by ajkerrigan** [comment]
No need to open a new issue, your point is well taken. The big bang black approach is a concentrated burst of pain to make things smoother in the long term.

It does take some planning and consideration though, and there are several possible stops (both manual and automated) between things as they are today and "black everything".

**Comment by kapilt** [comment]
I've been wondering if we can to this more piecemeal then a break every pr way. we've already got black running on some directories in tools. I think the goal would be to move individual directories over based on a lack of extant prs to them.
