### ISSUE TITLE
Latest Docker images aren't CodeBuild compatible any more

### ISSUE THREAD

**Issue by nerdyness** [cloud-custodian/cloud-custodian#5560]
**Describe the bug**
I run custodian & c7n-org via AWS CodeBuild. This used to work fine in the past however since the latest changes to the Docker images (probably [this commit](https://github.com/cloud-custodian/cloud-custodian/commit/a09e4ab946994ad4255ac3a9da727a8ec1ae3a74#diff-3254677a7917c6c01f55212f86c57fbf)) I get the following error during the provisioning phase:
"SINGLE_BUILD_CONTAINER_DEAD: Build container found dead before completing the build. Build container died because it was out of memory, or the Docker image is not supported."

A bit of research brought me to [this](https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#windows-server-core-version). Looks like the new base image is somehow incompatible with AWS CodeBuild. I've tested this for both [cloudcustodian/c7n](https://hub.docker.com/r/cloudcustodian/c7n/) and [cloudcustodian/c7n-org](https://hub.docker.com/r/cloudcustodian/c7n-org/) images and it's currently no longer AWS CodeBuild compatible. I can confirm this was working as recently as Tuesday, 31st March.

I happened to have a version from last week's [cloudcustodian/c7n](https://hub.docker.com/r/cloudcustodian/c7n/) and [cloudcustodian/c7n-org](https://hub.docker.com/r/cloudcustodian/c7n-org/) images which I've pushed into ECR and that is working fine.

**To Reproduce**
Create an AWS CodeBuild project that uses the [cloudcustodian/c7n](https://hub.docker.com/r/cloudcustodian/c7n/) Docker image to execute the steps in buildspec.yml.

The container doesn't even launch now, the LogGroup and LogStream is being created in CloudWatch however nothing is being logged.

**Expected behavior**
AWS CodeBuild to run my Cloud Custodian builds.

**Additional context**
It'd also be good to have some kind of versioned Docker image instead of just "latest". The short commit SHA would be enough so I can at least reference the image on Docker hub instead of hosting my own.

**Comment by kapilt** [comment]
- you'll need to provide an example buildspec, ie what are you doing with the container? 
- the new containers are significantly smaller and have passed several validation tests.
- re latest you every image build has an image id if you want to reference a historical one, based on sha checksum of the layers.
- support for CodeBuild sounds good, but a reference to what binaries/tools codebuild expects to find in the image would be helpful.. this was the closest I found in casual search and shows awscli, git https://aws.amazon.com/blogs/devops/extending-aws-codebuild-with-custom-build-environments/ albeit its unclear what's required, but thats also based on your usage (buildspec), which is also unclear.

**Comment by nerdyness** [comment]
* **buildspec.yml**:
```
version: 0.2

phases:
  build:
    commands:
      - custodian validate ./custodian/policies/*
      - custodian run --output-dir ./custodian/output ./custodian/policies/*
```
In `custodian/policies/` are only a few sample policies taken from the documentation, they don't matter for this since CodeBuild doesn't even start the container.

CodeBuild overwrites the default entrypoint of the custodian executable so you have to provide the executable as well in the buildspec file.

* RE `latest`, I can see the [list of builds](https://hub.docker.com/r/cloudcustodian/c7n/builds) on Docker Hub but how do I then reference that image if the tag is always latest? I can see the sha checksum you mention once I have the image downloaded but I don't see a history of images with that tag.

* CodeBuild doesn't require much - I don't think you need any particular binaries apart from maybe a shell? That could be the issue. I haven't looked at distroless containers before and just saw that they don't include a shell. I could also be the operating system type. As per the [AWS documentation](https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html#windows-server-core-version), this error occurs when you try to launch the wrong OS type (i.e. a Windows container on a Linux cluster), maybe CodeBuild has a problem with the distroless containers?

Personally, I like to use the c7n-org container since it contains custodian, c7n-org and c7n-mailer (potentially more) and I don't think the image needs any more.

**Comment by kapilt** [comment]
so what's required in a code build image...
 https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

aka amazon linux 2 or ubuntu 18.04 with an arbitrary set of additional binaries afaics.

listed out for codebuild's idiosyncratic nomenclature on ubuntu standard 4 (all 4 versions are on 18.04) that's https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile 

afaics, codebuild wants dozens of binaries and large/bloated images, some portion of which is required to work. we're publishing minimal containers by default because that helps users using every container platform and reduces security footprint on installed software. codebuild isnt a container platform its a ci environment, which has very specific requirements, subject to change without notice. our previous images we had weren't ubuntu, so technically were also unsupported by codebuild. i'm open to publishing a codebuild image, but this isn't docker, kubernetes, nomad.. where the object is to run a container, its a closed source ci platform with arbitrary changes on the binaries required in a custom image.

**Comment by nerdyness** [comment]
I'm sorry if I haven't been clear with my ask here and we are misaligned on what images CodeBuild can run.

We need to make a distinction here between images CodeBuild **provides** and images CodeBuild **supports**. I don't expect there to be a drop-down in the AWS CodeBuild console where I can select custodian from the list of CodeBuild provided images. Instead, you can specify a custom image from either ECR or the DockerHub and `cloudcustodian/c7n` was working fine. 

The image you specify doesn't need to be based on one of the provided images, it just needs to be Linux.

I think the problem is that CodeBuild only supports Linux containers and using a distroless container image doesn't have this flag/tag/setting and hence CodeBuild won't run that image.

Ideally there is some way to set this flag/tag/setting in the distroless container image to say `OS=Linux`, so that I can specify `cloudcustodian/c7n` and CodeBuild can still execute the image pulled from the Docker hub.

**Comment by kapilt** [comment]
maybe there is some misunderstanding around containers. containers are really just tarballs of union/layered filesystems. distroless is a marketing phrase, these are linux containers which is why every linux container platform runs them. codebuild is not a container platform, its a ci system that happens to use containers, and has unspecified requirements on whats in them. you can use docker inspect to verify OS/Arch on the image (linux/amd64). os/arch refers to the sys call and binary arch compilation of assets in the tarball.

the issue your having is very much about codebuild not specifying what it needs in a container, it could be bash, git, or a dozens of other things.  the error your referencing re windows containers is really completely unrelated, its just the only documentation related to a generic internal error. resolving this across thee project product images  is either, contacting your tam to ask the service team to publicly document what they expect in a container (binary and path). trial and error permutations of image building, to figure what's missing by adding random binaries to see if it resolves. publishing a special codebuild image thats contains the kitchen sink.

**Comment by nerdyness** [comment]
Okay, I think I get you now.

The error AWS CodeBuild throws is pretty generic and the operating system type is a red herring - the real issue is probably that CodeBuild, by it's very nature of being a build service expects to run a bunch of scripts/commands and thus expects at the very least a shell. The distroless container doens't offer one so it crashes...

I'm hoping I'll find some time over the Easter break to confirm this theory and we can maybe publish a `cloudcustodian/c7n:dev` image that contains a shell or whatever else is needed to be CodeBuild compatible.

Thank you for your patience 😄

**Comment by kapilt** [comment]
fwiw, i'm experimenting on this as well. it looks like this will bump images up another 62mb images to use an ubuntu:20.04 base container with the multi-stage build. the alternative is that we package a parallel set of images on c7n-org/c7n for codebuild.  ala cloudcustodian/cli-codebuild:dev, cloudcustodian/c7n-org-codebuild:dev  but thats going to get messy, more so if we start doing differential builds by provider.

@FireballDWF thoughts?

**Comment by kapilt** [comment]
i'm starting to wonder if we just need to start publishing the distro less ones as slim variants, and stick to a deb/ubuntu base for the existing images.

**Comment by kapilt** [comment]
#5571 will switch the default images to ubuntu:20.04 (lts albeit unreleased), its about a 62mb increase. we'll continue to maintain the distroless images as a `-distroless` suffix'd variant.

**Comment by nerdyness** [comment]
👍 thanks for the update, @kapilt. I didn't get around to play with this over Easter but this looks like a good outcome
