### ISSUE TITLE
Feature Request: `report` CLI Functionality as Lambda Function

### ISSUE THREAD

**Issue by jcderose** [cloud-custodian/cloud-custodian#5587]
**Is your feature request related to a problem? Please describe.**
We currently deploy Cloud Custodian in AWS on an EC2 instance to scan multiple accounts (via the `c7n-org` package and `run` CLI command), generate a report (via the `report` CLI command), and upload the results to S3. In an effort to increase ephemerality of our compute resources, we'd like to move the entire setup (both `run` and `report` functionality) into Lambda. 

Cloud Custodian allows users to execute a policy as a Lambda function (e.g. a subcomponent of the CLI `run` functionality), based on the `mode` parameter of that particular policy in the policy file. But the `report` CLI functionality is not supported inside Lambda.

**Describe the solution you'd like**
I imagine the functionality would look similar to the `report` CLI command but in Python function form. The function already exists in `cloud-custodian/c7n/reports/csvout.py` but there's no way to call it from inside a Python script.
```
def report(policies, start_date, options, output_fh, raw_output_fh=None):
    """Format a policy's extant records into a report."""
```
https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/reports/csvout.py

**Describe alternatives you've considered**
- Deploying our Custodian setup in ECS - the `run` functionality can easily run as an ECS task but the `report` functionality requires a bit more overhead to copy `run` results from S3 and upload the resulting report afterwards. This is an anti-pattern to ECS's model of "one container, one command".
- Build our own `report` functionality in Python. Totally doable but totally a pain. I'd rather improve the existing wheel than build my own, so-to-speak.

**Comment by kapilt** [comment]
I'm not even sure what you mean by run report in a lambda. you'll have to a bit more detailed with regard to your expectations of that outcome.

also your rationality on ecs seems.. odd, its container compute... ie. its general purpose.  if you want to run a separate task for reports, then do so.  

as always contributions welcome.

**Comment by jcderose** [comment]
I'd be happy to provide more details. What portion of my suggested solution would you like me to explain? 

Regarding ECS - running the `report` command requires the `run` results already exist on the local storage. Since the results will be in S3, my `report` ECS task will need to download them to disk before running the `report` command. This means I've already broken the ECS model of "one container, one command" since I'll need one command to download the files and one command to run the `report` CLI command.

**Comment by kapilt** [comment]
regarding lambda report, and a complete example..  how do you want to spell it in a policy, and what should it do.  ie generate a csv report on the policy execution/ lambdas own run or report on other runs, and output to where? ie. an example of the policy content and expected behavior, the more detailed the better. 

regarding ecs, report doesn't require output locally, and even then ecs (i'm assuming you mean fargate btw) has efs support, so yeah.. that use case totally works with separate ecs containers, and even sans efs sticking a front end shell script is pretty trivial...

**Comment by jcderose** [comment]
I've updated my original post with more details about my requested solution. Let me know if that helps answer your questions or if you need me to provide more information.

As for ECS - `report` does require execution output locally. Or at least, `c7n-org report` does: https://github.com/cloud-custodian/cloud-custodian/issues/4029. And this functionality that I'm requesting should work for both `custodian` and `c7n-org`.

**Comment by kapilt** [comment]
your original post is not showing any updates.... so still missing what your talking about.. but re-rereading.. and restating what I've already have in this issue.

first custodian doesn't have a python api,  its an application, wrt to the internals we don't have stability guarantees wrt to attempts to use that, and stuff will break.. see for example the api for pip (hint, its the cli).

second, this use case seems to be better suited to ecs, your philosophical concerns don't make sense given its exactly the usage you want (run, report). to me this is the equivalent of a mental hang up if a container can execute a shell script that have multiple commands.

third, you've not actually clearly articulated what you actually want this feature to look like. ie. when I add y to this policy, x happens when the cli runs it. or in the case of a lambda policy, when event is received it does y.

**Comment by kapilt** [comment]
spending some time inferring intent.. i think what your looking for is maybe an action that outputs to csv to s3, but you'll have to confirm. note, that `notify` already exists as a data stream action.

**Comment by kapilt** [comment]
even with a policy csv write action, its a little unclear as to the utility, ie. on a cloud trail policy lambda, given a thousand event invocations, you'd end up with a thousand one line csvs. additionally, we already have structured outputs for lambdas to s3, to which the csv format is lossy to.  absent a concrete use case / business value, and a expression of what this would look like its not clear why this makes sense.
