### ISSUE TITLE
Want to identify all of the Public IP Address associated with AWS accounts

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#6335]
**Is your feature request related to a problem? Please describe.**
We would like to know all of the public ip addresses being used in the AWS account (what address is used by what resources and what regions). This will help us during incident response or general checkup / lookup.

**Describe the solution you'd like**
Found another tool on github- https://github.com/arkadiyt/aws_public_ips
Don't want to use something else. We want to see if cloud custodian can do this.

**Describe alternatives you've considered**
I have seen this page at AWS documentation- https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html which allows us to grab everything (service includes all the resources that supports public ip addressing). I tried looking in cloud custodian documentation and couldn't find the resource type that i should used.....(not even in aws.account)

**Additional context**

**Comment by kapilt** [comment]
could you be a little more specific on what an example policy is and what outputs your looking to include. its a little bit unclear what your goal is you, you talk about public ips associated to resources of a single account as well as public resources associated to *every* aws account which are *very* different things.

let's be a little more clear, what resources your trying to include, ips on cloud front, s3, load balancers, ec2, etc, etc. the former (minus ec2) are all transient and aliased to a pool of ips using SNI, and also coming up a level what's the goal here?

**Comment by kapilt** [comment]
after some more reflection i don't think this belongs in custodian. its not really a policy that you want to enforce on the environment, its a database of ips. even generating a report here though across resources will be mostly useless due to staleness as for many of the applicable resource ips, they are dynamic with ttls that as low single digit seconds. moreover the ip address lookup is also subject to particulars of the resolution host's dns setup (r53 resolver, local dns setup, vpc endpoints, etc).
