### ISSUE TITLE
AWS: Add CW Event-Rule to Service Limit Increase or Vice Versa

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#6723]
**Is your feature request related to a problem? Please describe.**
We would like to write a cloud custodian policy that can look for the CW event rule quota (default is 400) and if it passes 80% of the quota- it must request an increase in quota by submitting the service /support ticket. This increase can be 25%.  

As we write more policies we are coming to FULL utilization of the CW event-rule service quota. Due to this, our pipeline fails and policy fails to get deployed. By introducing this policy, the custodian will manage this automatically and we just need to look at the status.

**Describe the solution you'd like**
Custodian to submit the support ticket to increase the CW event rule - provide all data to support ticket as needed.

**Describe alternatives you've considered**
At the moment we are doing this manually on an account basis.

**Additional context**
Since service limit works on resource type: aws.accounts and not on aws.event-rule not sure if we can introduce a new filter into event-rule to handle this quota increase via separate filter/action.

**Comment by ajkerrigan** [comment]
Hi @aakifshaikh - you're not alone! There is an existing pull request in the works that aims to add service quota filters and actions to support this case. You can follow along in #6511. I'm going to close this issue, since that PR is effectively a generalization/expansion of the ask here. Let me know if I'm missing anything though, thanks.
