### ISSUE TITLE
1.13 – Ensure MFA is enabled for the root user (CIS Benchmark)

### ISSUE THREAD

**Issue by haiauth** [cloud-custodian/cloud-custodian#7264]
### Ask your question

I am trying to understand the output of the policy that ensures MFA is enabled for root user. When I looked at the `resources.json` file, I can see the AccountMFAEnabled: 1 but I don't understand what that even means. It also says I have 12 MFA devices and all of them are in use. While, I have 11 users and all of them have MFA set. I am so confused, lol! 

Is there any way I could just check if MFA is enabled or not? I need to put this into a report and that output is not so useful. I tried the `report` feature, did not work for me (but that is a different story). 

### Policy

```shell
policies: 
  - name: iam-root-keys-no-mfa-audit
    comment: |
      Determine if an account has either not been enabled with root MFA or has root API keys.
    resource: account
    filters:
      - type: iam-summary
        key: AccountMFAEnabled
        value: false
        op: eq
        value_type: swap
    actions: 
      - type: notify
```

### Relevant log/traceback output

```shell
[
  {
    "account_id": <ACCOUNT_ID>,
    "account_name": "<ACCOUNT_NAME>",
    "c7n:iam_summary.GroupPolicySizeQuota": 5120,
    "c7n:iam_summary.InstanceProfilesQuota": 1000,
    "c7n:iam_summary.Policies": 26,
    "c7n:iam_summary.GroupsPerUserQuota": 10,
    "c7n:iam_summary.InstanceProfiles": 1,
    "c7n:iam_summary.AttachedPoliciesPerUserQuota": 10,
    "c7n:iam_summary.Users": 11,
    "c7n:iam_summary.PoliciesQuota": 1500,
    "c7n:iam_summary.Providers": 1,
    "c7n:iam_summary.AccountMFAEnabled": 1,
    "c7n:iam_summary.AccessKeysPerUserQuota": 2,
    "c7n:iam_summary.AssumeRolePolicySizeQuota": 2048,
    "c7n:iam_summary.PolicyVersionsInUseQuota": 10000,
    "c7n:iam_summary.GlobalEndpointTokenVersion": 1,
    "c7n:iam_summary.VersionsPerPolicyQuota": 5,
    "c7n:iam_summary.AttachedPoliciesPerGroupQuota": 10,
    "c7n:iam_summary.PolicySizeQuota": 6144,
    "c7n:iam_summary.Groups": 2,
    "c7n:iam_summary.AccountSigningCertificatesPresent": 0,
    "c7n:iam_summary.UsersQuota": 5000,
    "c7n:iam_summary.ServerCertificatesQuota": 20,
    "c7n:iam_summary.MFADevices": 12,
    "c7n:iam_summary.UserPolicySizeQuota": 2048,
    "c7n:iam_summary.PolicyVersionsInUse": 65,
    "c7n:iam_summary.ServerCertificates": 0,
    "c7n:iam_summary.Roles": 96,
    "c7n:iam_summary.RolesQuota": 1000,
    "c7n:iam_summary.SigningCertificatesPerUserQuota": 2,
    "c7n:iam_summary.MFADevicesInUse": 12,
    "c7n:iam_summary.RolePolicySizeQuota": 10240,
    "c7n:iam_summary.AttachedPoliciesPerRoleQuota": 15,
    "c7n:iam_summary.AccountAccessKeysPresent": 0,
    "c7n:iam_summary.GroupsQuota": 300
  }
]
```

**Comment by ajkerrigan** [comment]
You're on the right track for sure with that policy. Your `op: eq` is implied, since `eq` is the default op. And because `key equals value` means the same thing as `value equals key`, `value_type: swap` isn't necessary.

As for just displaying the `AccountMFAEnabled` piece of the credential report... `custodian report` isn't a bad option actually :). It won't include the IAM summary details by default, but you can use `--field <name>:<jmespath expression>` to add additional columns to the report. So to include a column showing whether root user MFA is enabled for an account, you could use:

```
custodian report \
    --output-dir /my-output-directory \
    --field 'AccountMFAEnabled="c7n:iam_summary".AccountMFAEnabled == True' \
    /path/to/my/policy.yaml
```

Where the `== True` piece will make your report show `True` or `False` rather than the report's `0` or `1`. If you're having issues running `custodian report`... you're right that's probably a separate issue.

**Comment by haiauth** [comment]
Got it. Thanks so much!!
