### ISSUE TITLE
Error when sending logs from Lambda to s3 buckets in another region

### ISSUE THREAD

**Issue by sean-zou** [cloud-custodian/cloud-custodian#7593]
### Describe the bug

Getting this error when sending logs from Lambda to s3 buckets in another region. After revert this PR the error went away: https://github.com/cloud-custodian/cloud-custodian/pull/7524

>  [ERROR] ClientError: An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
> Traceback (most recent call last):
>   File "/var/task/custodian_policy.py", line 4, in run
>     return handler.dispatch_event(event, context)
>   File "/var/task/c7n/handler.py", line 165, in dispatch_event
>     p.push(event, context)
>   File "/var/task/c7n/policy.py", line 1236, in push
>     return mode.run(event, lambda_ctx)
>   File "/var/task/c7n/policy.py", line 537, in run
>     return PullMode.run(self)
>   File "/var/task/c7n/policy.py", line 282, in run
>     with self.policy.ctx:
>   File "/var/task/c7n/ctx.py", line 73, in __enter__
>     self.initialize()
>   File "/var/task/c7n/ctx.py", line 47, in initialize
>     self.output = blob_outputs.select(self.options.output_dir, self)
>   File "/var/task/c7n/output.py", line 52, in select
>     return self[k](ctx, parse_url_config(selector))
>   File "/var/task/c7n/resources/aws.py", line 539, in __init__
>     region = s3_client.get_bucket_location(Bucket=self.bucket)['LocationConstraint']
>   File "/var/runtime/botocore/client.py", line 391, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/var/runtime/botocore/client.py", line 719, in _make_api_call
>     raise error_class(parsed_response, operation_name)

### What did you expect to happen?

When running in Lambda mode, it should be able to send logs to s3 buckets in another region

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
master
```

**Comment by ajkerrigan** [comment]
Hi @sean-zou - thanks for reporting this. #7524 seems like a necessary change to avoid breakages when running in certain regions. But it looks like as a side effect will break some existing cases of working execution roles that don't have `s3:GetBucketLocation` permissions for their target output buckets.

Excluding that PR from your environment seems an effective workaround, and granting `s3:GetBucketLocation` for the output bucket would also work. The permission gap may be in your IAM role, the S3 bucket policy, or elsewhere (since IAM has many ways to say no).

I suspect we will also want to catch this case and fall back to the original behavior to avoid surprises like this (that is, fall back to us-east-1 if we're unable to determine the bucket region due to permission errors). Thanks again for the detailed report :+1: .

**Comment by kapilt** [comment]
this looks primarily like a permission issue wrt to the lambda execution role. its a fairly innocuous, basic permission wrt to s3 interactions re s3:GetBucketLocation

**Comment by castrojo** [comment]
Note to selves, we should update the docs here to mention that the s3 bucket needs the proper permissions: https://cloudcustodian.io/docs/aws/lambda.html#execution-options

**Comment by scoleri** [comment]
Should we have a whole section of the docs for lambda execution role policies?  There are many cases where a generic policy wouldn't get you all the permissions you need.  In this specific issue, it would only affect you if you were using resource s3 cross-region.  This problem exists for anything you do in AWS not specific to custodian.

**Comment by sean-zou** [comment]
I'm pretty sure it is not IAM role access issue.

Check out this issue, and I believe this comment is the right solution: https://github.com/aws/aws-sdk-go/issues/720#issuecomment-613038544

**Comment by kapilt** [comment]
what region is the lambda in and what region is the bucket in?

**Comment by kapilt** [comment]
fwiw this should get closed with #8289
