### ISSUE TITLE
document docker image usage

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#815]
we've currently got some deficiencies wrt to platforms (win32 and closed tempfile usage) and packaging up when installed via system python on distros. we should address those, but we're already publishing per commit docker images and should document their usage, additionally we need to tag our docker images for releases.

**Comment by amphibithen** [comment]
this is very confusing, because i had this working earlier in 2017 but now it stopped working.  from earlier this year, this worked:
`docker run -v $PWD:/var/log/cloud-custodian -e AWS_DEFAULT_REGION=us-east-1 docker.io/capitalone/cloud-custodian run -c /var/log/cloud-custodian/mypolicy.yml -s /var/log/cloud-custodian`
however when i run the same now, i get:
`2017-08-02 20:16:16,113: custodian.cli:DEBUG using default region:us-east-1 from boto
2017-08-02 20:16:16,415: custodian.commands:ERROR policy file does not exist (/var/log/cloud-custodian/Offhours/ec2-cpu-underutilized.yml)
2017-08-02 20:16:16,415: custodian.commands:ERROR Found 1 errors. Exiting.`

however i can docker cp the file out with the path mentioned in the log file, so i know it works.  i have tried opening permissions of files, changing the run command, etc. and i cant for the life of me figure out how to get it to run now...

**Comment by amphibithen** [comment]
for those of you who may have had the same issue, apparently this is stopped working due to either a docker version upgrade or a base image update from custodian.  have to append :z to the end of volume mapping:
`was this`
```
docker run -v $PWD:/config -e AWS_DEFAULT_REGION=us-east-1 capitalone/cloud-custodian run -s out /config/ec2.yml
```
` is now this`
```
docker run -v $PWD:/config:z -e AWS_DEFAULT_REGION=us-east-1 capitalone/cloud-custodian run -s out /config/ec2.yml
```

**Comment by sthanushkodi** [comment]
is there a step by walk through of how to run cloud custodian in docker on windows?  if someone can point  me to it, it would be super helpful. thanks

**Comment by k7faq** [comment]
I am unable to use this feature. The inclusion of ":z"  does not correct the issue(s) for me.
this is using the container pulled from docker hub `docker pull capitalone/cloud-custodian`

```
docker run -v $PWD:/config:z -e AWS_DEFAULT_REGION=us-east-1 capitalone/cloud-custodian run -s out my-policy.yml 
2019-02-12 16:04:47,594: custodian.commands:ERROR policy file does not exist (my-policy.yml)
2019-02-12 16:04:47,594: custodian.commands:ERROR Found 1 errors.  Exiting.
```

```
$ cat my-policy.yml 
policies:
  - name: steven-test-policy
    resource: ec2
    filters:
    - "tag:Custodian": present
    actions:
    - stop(custodian) 
```

Please advise as to what I am doing wrong. Even using the example provided on the docker hub page does not work:
```
function main () {
  docker run \
    -it \
    -v "${HOME}/.aws:/custodian/.aws:ro" \
    -v "${PWD}/logs:/tmp" \
    -v "${PWD}/.cache:/custodian/.cache" \
    -v "${PWD}/policies:/custodian/policies:ro" \
    -e AWS_DEFAULT_REGION='us-east-1' \
    capitalone/cloud-custodian run --output-dir=/tmp \
    policies/my-policy.yml
}

main
```

**Comment by kapilt** [comment]
the docker hub image is ancient, recommend is to build a docker image if you want to use docker (dockerfile up to date), if you do a non relative path to the config does that resolve re final path parameter?

**Comment by sthanushkodi** [comment]
@k7faq,
  I ended up switching over to using a cloud9 environment and developing policies and running c7n from there. All the jumping through hoops to get it running in windows went away. Not sure what your requirements and constraints are, but It would be worth looking into it if you havent already.

**Comment by kapilt** [comment]
fwiw windows is officially supported, and custodian now does publish official and supported docker images
