### ISSUE TITLE
"{now}" throws an error with c7n 0.9.26

### ISSUE THREAD

**Issue by billjorgensen** [cloud-custodian/cloud-custodian#8503]
I updated c7n, c7n-org and c7n-mailer and found an issue with the use of "{now}" as a date when it comes to a tag value for AWS resources (EC2, RDS, etc).

I get 
error:Object of type FormatDate is not JSON serializable
when designating a date as "{now}". Here is an example from one of the policies that fail with this message
   actions:
      - type: tag
        key: c7n_health_check
        value: "{now}"

From my requirements.txt for the CodeBuild pipeline
c7n==0.9.26
c7n-org==0.6.25
c7n-mailer==0.6.25

Is this related to https://github.com/cloud-custodian/cloud-custodian/issues/7916?

**Comment by billjorgensen** [comment]
I rolled back to these and I have no issues with the date format related to "{now}"
# c7n-org
c7n==0.9.18
c7n-org==0.6.17
c7n-mailer==0.6.17

**Comment by ajkerrigan** [comment]
Looks like this is because it's trying to expand that `{now}` when provisioning the Lambda function rather than at policy runtime. I suspect that even in 0.9.18 that's probably not what you want. The true fix for this is probably to make sure we're deferring that `{now}` expansion until runtime. A more immediate workaround would be to handle that manually. If you double the braces:

```yaml
type: tag
key: c7n_health_check
value: "{{now}}"
```

Then when Custodian provisions a Lambda function it'll replace `{{now}}` with `{now}`. And then when the policy fires, it'll sub in the current date.
