### ISSUE TITLE
rds filter/action - filter storage metrics, resize

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#934]

**Comment by kapilt** [comment]
wip in https://github.com/kapilt/cloud-custodian/tree/rds-resize

**Comment by whit537** [comment]
Taking a look at this. Verbose log in https://github.com/whit537/cloud-custodian/pull/11.

**Comment by whit537** [comment]
@kapilt I've got resizing-up just about ready to go in https://github.com/whit537/cloud-custodian/pull/11. I'm going to work on the action improvements next.

Resizing down is more complicated, because AWS doesn't give us a direct API there ([`ModifyDbInstance`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html) only resizes up). We can create and promote a read replica for MySQL/Maria and Postgres. Otherwise I guess we're looking at a snapshot/recreate/reload during the maintenance window. Is that line with what you were expecting for this case?

**Comment by whit537** [comment]
Confirmed on weekly call that resize down is a mess. Deprioritized for now, will get PR in for resize up and revisit later.

**Comment by whit537** [comment]
Easy half in https://github.com/capitalone/cloud-custodian/pull/1051.

**Comment by kapilt** [comment]
feels like what can be done on this (resize up on metrics) is already done. resize down isn't really supported by the service without userspace dump/restore, so closing out.
